name: Deploy Production 🚀

on:
  release:
    types:
      [created, published, edited]

jobs:
    deploy-production:
        name: Deploy to production server 🚀
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Execute deployment command
              uses: appleboy/ssh-action@v1.0.3
              env:
                APP_PROD_PORT: ${{ secrets.APP_PROD_PORT}}
                MINIO_PROD_ENDPOINT: ${{ secrets.MINIO_PROD_ENDPOINT}}
                MINIO_PROD_ACCESS_KEY: ${{ secrets.MINIO_PROD_ACCESS_KEY}}
                MINIO_PROD_SECRET_KEY: ${{ secrets.MINIO_PROD_SECRET_KEY}}
                APP_PROD_PATH: ${{ vars.APP_PROD_PATH}}
                APP_TAG: ${{ github.event.release.tag_name }}
            
              with:
                host: ${{ secrets.SSH_HOST_PRODUCTION}}
                username: ${{ secrets.SSH_USER_NAME_PRODUCTION}}
                key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION}}
                envs: APP_PROD_PORT, MINIO_PROD_ENDPOINT,MINIO_PROD_ACCESS_KEY, MINIO_PROD_SECRET_KEY, APP_PROD_PATH
                script:

                    if [[ -d "${APP_PROD_PATH}" ]]; then 
                        cd $APP_PROD_PATH
                        sudo docker compose down pacmusic-prod
                        git pull origin main
                    else
                        ssh-keyscan github.com > ~/.ssh/known_hosts
                        git clone $GIT_URL $APP_PROD_PATH
                        cd $APP_PROD_PATH
                    fi

                    echo "APP_IMAGE=${DOCKERHUB_USERNAME}/pacmusic" > .env
                    echo "APP_TAG=$APP_TAG" >> .env
                    echo "APP_PROD_PORT=$APP_PROD_PORT" >> .env
                    echo "MINIO_PROD_ENDPOINT=$MINIO_PROD_ENDPOINT" >> .env
                    echo "MINIO_PROD_ACCESS_KEY=$MINIO_PROD_ACCESS_KEY" >> .env
                    echo "MINIO_PROD_SECRET_KEY=$MINIO_PROD_SECRET_KEY" >> .env
                    
                    sudo docker compose up --build --detach pacmusic-prod

            - name: Hit Endpoint
              run: |
                sleep 10
                curl ${{ secrets.PROD_URL}}
